### ISSUE TITLE
concatenate失敗,好像是模型類別不對應?

### ISSUE THREAD

**Issue by guofenggitlearning** [wangzhongju/data_filter_tool#2]
Traceback (most recent call last):
  File "./v3_detect.py", line 255, in <module>
    detect.detect()
  File "./v3_detect.py", line 227, in detect
    pred_bbox = np.concatenate([np.reshape(pred_sbbox, (-1, 5 + self.num_classes)),
  File "<__array_function__ internals>", line 6, in reshape
  File "/home/oem/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 299, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/oem/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 689520 into shape (18)
Traceback (most recent call last):
  File "./v2_detect.py", line 184, in <module>
    weight = torch.load(weight_file)
  File "/home/oem/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 595, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/oem/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 766, in _legacy_load
    raise RuntimeError("Invalid magic number; corrupt file?")
RuntimeError: Invalid magic number; corrupt file?
a b c d: 0 0 0 0
Now write all results to txt file
00001
2022.01.26
Traceback (most recent call last):
  File "./python/filter_res.py", line 32, in <module>
    tar_list = os.listdir(osp.join(path1, "tar"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/oem/pgf/data_filter_tool/data/tar'
All pass, you can check the result in ./data/result/{the_folder_you_define}/ && ./res/{the_folder_you_define}/

**Comment by guofenggitlearning** [comment]
(Pdb) pred_sbbox.shape
(1, 52, 52, 3, 85)
(Pdb) self.num_classes
13
(Pdb) pred_mbbox.shape
(1, 26, 26, 3, 85)
(Pdb) pred_lbbox.shape
(1, 13, 13, 3, 85)
(Pdb) np.reshape(pred_sbbox,(-1,5+self.num_classes))
*** ValueError: cannot reshape array of size 689520 into shape (18)
